### ISSUE TITLE
Support for older Python versions

### ISSUE THREAD

**Issue by MashMB** [qwertyquerty/pypresence#1]
Hello,
Nice to see so developed Discord RPC library in Python. I was working on simple RPC client but I did not wrapped full SDK (no needed for me). It will be really nice if you can get rid of asyncio because not all of users will be using that with the newest version of Python interpreter.
Good work,
Cheers

**Comment by MashMB** [comment]
You can see my client on my GitHub account. Yes I know that it requires big rewrite but maybe in the future?

**Comment by LewdNeko** [comment]
Support for Python < 3.x is simply not something I see this project being able to reasonably support. As it stands, this project currently doesn't even support Python 3.4 (fix for this coming soon). Python 2.x support is just not possible.

**Comment by qwertyquerty** [comment]
Agreed. But yes, python 3.4 support will be soon.

**Comment by LewdNeko** [comment]
Python 3.4 Support has been added. Please close this issue
