### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by jellytoaster** [qwertyquerty/pypresence#102]
I'm trying to make a rich presence that links to a rickroll(yes a rickroll), but whenever i try to do this, i get an TypeError.

`Traceback (most recent call last):
  File "c:/Users/-/Downloads/Guessing game/guessnumber.py", line 450, in <module>
    mainmenu()
  File "c:/Users/-/Downloads/Guessing game/guessnumber.py", line 405, in mainmenu
    game()
  File "c:/Users/-/Downloads/Guessing game/guessnumber.py", line 356, in game
    discordpresence.update(details="Finished a game", state="Took " +  str(timeelasped) + " seconds", large_image="questionmark", large_text="XD", buttons=[{"label": "Click here", "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"}])
TypeError: update() got an unexpected keyword argument 'buttons'`

Here's my code:

`    discordpresence.update(details="Finished a game", state="Took " +  str(timeelasped) + " seconds", large_image="questionmark", large_text="XD", buttons=[{"label": "Click here", "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"}])`

**Comment by takipsizad** [comment]
async?

**Comment by jellytoaster** [comment]
wait i need async???? thought discord.py uses async not python

**Comment by jellytoaster** [comment]
even if i did need async how do i do it????

**Comment by Hunter2807** [comment]
@jellytoaster I suggest you to join the official discord server so that we can help you better. Here is the link to the same --> https://discord.gg/vYQ2uzUHPD . It will be easier for both of us...

**Comment by jellytoaster** [comment]
@Hunter2807 fun fact i joined it 2 days ago

**Comment by Hunter2807** [comment]
Oh haha, then I suggest u to ask the question there, it would be easy!

**Comment by jellytoaster** [comment]
@Hunter2807  go in pypresence support channel

**Comment by Hunter2807** [comment]
@jellytoaster please close this Issue if you are done..

**Comment by et-sollertis-animi** [comment]
@jellytoaster i had this problem as well. all you need to do is run:
```pip uninstall pypresence```
and then
```pip install pypresence```
that updates the package

**Comment by qwertyquerty** [comment]
Or just `pip install pypresence -U`

**Comment by Nirbose** [comment]
Hello, I don't know why the button doesn't work on my profile... However I followed the letter that is in the example folder.

**Comment by Hunter2807** [comment]
@Nirbose pls make a new issue and post ur code, yr error and other stuff there, don't comment on an existing issue 🤦

**Comment by Nirbose** [comment]
Sorry 😅

**Comment by jellytoaster** [comment]
> @jellytoaster please close this Issue if you are done..

not done

**Comment by Hunter2807** [comment]
That error comes when yr pypresence installation is not updated. Try updating your pypresence installation to the latest version @jellytoaster
