### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by Mrx-dev** [qwertyquerty/pypresence#104]
# When i click the buttons not opening my website or any link i want :(

<img src='https://cdn.discordapp.com/attachments/805431589521588246/809932058373652510/unknown.png'>

**Comment by Hunter2807** [comment]
@Mrx-dev you can't click your own buttons

**Comment by Mrx-dev** [comment]
> @Mrx-dev you can't click your own buttons

then what the buttons do?

**Comment by Mrx-dev** [comment]
its work

**Comment by GiveMeSomeHowaHowa** [comment]
how do i get it to work?

**Comment by Hunter2807** [comment]
@GiveMeSomeHowaHowa what do u mean
