### ISSUE TITLE
Button problem 😅

### ISSUE THREAD

**Issue by Nirbose** [qwertyquerty/pypresence#105]
So here's my problem 😅, I try to make the button work, it displays well but the url doesn't work (_I completely copied and pasted the code given in the Example folder_).
There are no errors appearing on the Terminal/cmd.

**Comment by et-sollertis-animi** [comment]
This problem is affecting me too. When I click the button, it does not open the link.

**Comment by Hunter2807** [comment]
@et-sollertis-animi @Nirbose you can't click your own buttons. This is a discord thing. Not a library issue :)

**Comment by et-sollertis-animi** [comment]
Oh, well that's good to know. 👍
