### ISSUE TITLE
PyPresence not working for specific people

### ISSUE THREAD

**Issue by AngarosGamer** [qwertyquerty/pypresence#108]
Hello!
I'm working on an application that uses pypresence to display their status on Discord.
I've tested it, works for me, and I have a few other users for whom it also works.

Yet today someone messages me saying it didn't work. The code itself is running fine, the status just doesn't show at all!

I'm thinking it's an issue on the client side directly, but I'm not exactly sure.

Here's the code piece I use to connect to RPC:

`client_id = f.readline() # Read Discord application client ID

    try:

        RPC = Presence(client_id, pipe=0) # Presence system library

        RPC.connect() # Connect to discord user status

    except:

        PrintException()`

Where f is a file stored on the user's machine that contains their Discord application ID (app client ID).

Now I'm wondering if the issue isn't maybe coming from the fact that I specify a pipe, maybe I should just leave it blank?

P.S: I've made sure the user is on normal Discord, not canary, and that the application code is running on their machine with Discord open and connected at the same time, so that's not where the issue is emanating from.

Any help would be greatly appreciated!

**Comment by Hunter2807** [comment]
Hi @AngarosGamer ! Good to know you have an interest in PyPresence. But for us to help you more efficiently, I prefer you to join the discord server and close this issue here. You will be granted faster help there rather than here.. 

P. S- It would be good if you share some more code and stuff...

**Comment by AngarosGamer** [comment]
> Hi @AngarosGamer ! Good to know you have an interest in PyPresence. But for us to help you more efficiently, I prefer you to join the discord server and close this issue here. You will be granted faster help there rather than here..
> 
> P. S- It would be good if you share some more code and stuff...

Hey! Do you mind sending the Discord link in here?
In terms of code, I'll add anything you want! (not sure if discord is the place to send code, the character limit makes it difficult, especially since my code is quite beefy. 
Anyways, thanks, I'll be joining!

**Comment by Hunter2807** [comment]
https://discord.gg/vYQ2uzUHPD 

There ya go!

**Comment by LewdNeko** [comment]
Assuming this was resolved in the Discord. Re-open if not.
