### ISSUE TITLE
on_event not awaited - asyncio 

### ISSUE THREAD

**Issue by Jmarks199** [qwertyquerty/pypresence#113]
Possibly due to an update with asyncio, the asyncio  socket reader function feed_data() is not a coroutine. Actually, this could just be a bug with the pypresence api because feed_data is overridden to self.on_event in both the Client and AIOClient. 

bug occurs in BaseClient at the end here ->

if self._events_on:
            self.sock_reader.feed_data = self.on_event

my quick fix was to subclass AIOClient and override on_event back to a regular method (not async def) and then use asyncio.create_task() to run the callback coroutine:

if evt in self._events:
    asyncio.create_task((self._events[evt](payload["data"])))

sorry for being brief, but just wanted to alert the bug, this is a huge bug, so hard to imagine it's unknown.

**Comment by LewdNeko** [comment]
I think this is an issue with your usage of the library.

Please provided more detailed information or proper repro steps (and sample code) so this can be resolved.
