### ISSUE TITLE
License check fails on aur

### ISSUE THREAD

**Issue by MrSwedish** [qwertyquerty/pypresence#119]
```
==> Validating source files with md5sums...
    pypresence-4.2.0.tar.gz ... Passed
    LICENSE ... FAILED
==> ERROR: One or more files did not pass the validity check!
error downloading sources: python-pypresence
```
pls fix

**Comment by MrSwedish** [comment]
this is the right repository right?

**Comment by MrSwedish** [comment]
someone on the aur commented this:
```
 pouchkine commented on 2021-06-06 15:57	

Error with license:

I changed the sha256 to: '20be36b4067d3ba0c81b92359f6cc61199adbd4c026ef01ab6b18da5e3b9baa3' or the md5 to: '42b953de930ff1d8bfbde90feb4a612c'
```
try this please

**Comment by MrSwedish** [comment]
look at more comments, there is some useful stuff too
other than this issue

**Comment by LewdNeko** [comment]
What?

**Comment by MrSwedish** [comment]
okay, here is what you have to do:
replace the sha256 checksum with the newest one on the arch aur install script
then the license check will work, and this can be closed

**Comment by MrSwedish** [comment]
do this with every update, and you are good to go

**Comment by MrSwedish** [comment]
still fails

**Comment by qwertyquerty** [comment]
We do not maintain the arch aur install script
