### ISSUE TITLE
license fails aur

### ISSUE THREAD

**Issue by hiIexistlol** [qwertyquerty/pypresence#120]
hi, i'd like to report a problem that keeps me from installing this
your md5 in the aur is out of date with the license
here is the fixed md5:
`42b953de930ff1d8bfbde90feb4a612c`
change the lower one to this, and that should fix the problem, don't forget to do this tho
https://aur.archlinux.org/packages/python-pypresence/
fix this package or tell the maintainer the problem if you are not the maintainer

and stop putting your  P Y P R E S E N C E
everywhere, like it's SO COOL, no.. just stop its childish

ANYWAY, please a lot of people are having this problem you should fix it as soon as possible

**Comment by LewdNeko** [comment]
We **are not** responsible for anything listed on the link provided. Please contact the maintainer on that site instead. The only places we are responsible for distributing PyPresence from is:

https://pypi.org/project/pypresence/
https://github.com/qwertyquerty/pypresence

Attached shows that neither me nor Qwerty have anything to do with the AUR listing.
![A5D3660D-B198-411F-9093-58F5771CE1B9](https://user-images.githubusercontent.com/24483290/121778920-21a3a000-cb91-11eb-85be-1db52e7991e9.jpeg)

**Comment by hiIexistlol** [comment]
> fix this package or tell the maintainer the problem if you are not the maintainer
well, i wasn't entirely wrong, but rare requires THIS package and there is no way areound it sadly, tell the maintainer to fuck off or something, but rare needs it

**Comment by LewdNeko** [comment]
Are you aware of how this works? People releasing things for free in their spare time don't need people getting angry at them telling them to fuck off just because your day was mildly inconvenienced. 
What even is this 'rare' thing? Its definitely not something we're responsible for.

**Comment by hiIexistlol** [comment]
well, i don't why wrote 'fuck off'
well sorry to that guy, but rare is epic games launcher replacement that also works on linux, pretty cool
and it requires this, and it seems the maintainer has abandonded the package, if you could take ownership
that be pretty cool OR the maintainer finally maintains thier package

**Comment by LewdNeko** [comment]
If I'm honest I don't know if I want to take ownership and be responsible now after the two issues we just received writing angrily to us as if we're at fault here. And not being at my PC for a couple days, it's not something that'll get done with any urgency just so you can play fortnite on linux 😂

Please go and try get the AUR maintainer to respond as there is nothing we can do here right now.

regards,
N

**Comment by hiIexistlol** [comment]
not fortinte, the other free games
bruh
and read this please

> OR the maintainer finally maintains thier package

sorry if everything i type sounds angry, the last one wasn't supposed to this one neither

**Comment by hiIexistlol** [comment]
nevery anytime said you were the problem

**Comment by hiIexistlol** [comment]
and no urgency, i edited the install script and installed it that way
stop YOU beeing toxic

**Comment by qwertyquerty** [comment]
Pain

**Comment by JaredYoshi** [comment]
wtf
