### ISSUE TITLE
PermissionError: [WinError 5] Access is denied when code is Executed

### ISSUE THREAD

**Issue by NightMasterX** [qwertyquerty/pypresence#121]
Hey, I was building a Rich Presence application and it worked totally fine until today. When I ran the code today it no longer worked and I get a error, mind you I didn't change a single bit of code. Does anyone know what could the problem be? I have attached a SourceBin Link showing the error. Also I ran the code as admin and it worked but it doesn't show the Rich Presence.

https://srcb.in/yL8Hyycx4u
Thanks.

**Comment by SlashContext** [comment]
> Hey, I was building a Rich Presence application and it worked totally fine until today. When I ran the code today it no longer worked and I get a error, mind you I didn't change a single bit of code. Does anyone know what could the problem be? I have attached a SourceBin Link showing the error. Also I ran the code as admin and it worked but it doesn't show the Rich Presence.
> 
> https://srcb.in/yL8Hyycx4u
> Thanks.

Access is denied is a sense of missing permissions try allowing execution in administrator.

**Comment by LewdNeko** [comment]
Closing unless lack of privileges is not the issue - it should be thiugh.
