### ISSUE TITLE
Add `force` parrameter to `select_voice_channel`

### ISSUE THREAD

**Issue by Sebclem** [qwertyquerty/pypresence#122]
Hi,
The  `select_voice_channel` of `Client` does not have the `force` parameter that can be used if the user is already connected to a voice channel, this will "move" the user to the new channel.

Here the link to the doc: https://discord.com/developers/docs/topics/rpc#selectvoicechannel-select-voice-channel-argument-structure

**Comment by LewdNeko** [comment]
Must be new if it's missed - we don't scour the docs :P
