### ISSUE TITLE
pypresence won't work with PYQT5

### ISSUE THREAD

**Issue by MeblIkea** [qwertyquerty/pypresence#132]
Hi, this script work on another file, but  not on the main with PYQT5 window, and all
```
RPC = Presence('754224967968882788', pipe=1)
RPC.connect()
RPC.update(details='test1', state='test2')
```
I have  the error:
`FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type`
I think I have to use handler, but i don't know how to use it.
Thanks,

**Comment by FailSpy** [comment]
Carrying over from Discord for posterity:
https://discord.com/channels/499601462347956253/723444031102648391/874588236507394068
You mention on this message your pipe is `/run/user/1000/discord-ipc-0` but on your code with PyQT5 here, you specify a pipe of 1:
`RPC = Presence('754224967968882788', pipe=1)`

This will attempt to use `/run/user/1000/discord-ipc-1`. Try removing the pipe arg or specifying pipe=0 and see if that works better for you.

**Comment by LewdNeko** [comment]
@MeblIkea feel free to reopen if issue persists
