### ISSUE TITLE
Unable to Handshake on UNIX

### ISSUE THREAD

**Issue by Jmarks199** [qwertyquerty/pypresence#134]
Not suggesting this is a bug with the pypresence libray, but hoping that someone may have some insight. Starting today, my container started throwing this error during the startup process:

`09-23-2021 16:03:45.565 |ERROR |base_events.default_exception_handler:1707 |Task exception was never retrieved
algo_1  | future: <Task finished name='Task-3' coro=<startup() done, defined at /root/dob/bin/discord_server.py:47>

 exception=FileNotFoundError(2, 'No such file or directory')>

algo_1  | Traceback (most recent call last):
algo_1  |   File "/root/dob/bin/discord_server.py", line 49, in startup
algo_1  |     await client.start()
algo_1  |   File "/root/dob/dob/rpc_client.py", line 31, in start
algo_1  |     await super().start()
algo_1  |   File "/opt/conda/lib/python3.8/site-packages/pypresence/client.py", line 349, in start
algo_1  |     await self.handshake()
algo_1  |   File "/opt/conda/lib/python3.8/site-packages/pypresence/baseclient.py", line 128, in handshake
algo_1  |     self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
algo_1  |   File "/opt/conda/lib/python3.8/asyncio/streams.py", line 111, in open_unix_connection
algo_1  |     transport, _ = await loop.create_unix_connection(
algo_1  |   File "/opt/conda/lib/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
algo_1  |     await self.sock_connect(sock, path)
algo_1  |   File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
algo_1  |     return await fut
algo_1  |   File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
algo_1  |     sock.connect(address)
algo_1  | FileNotFoundError: [Errno 2] No such file or directory
`

It seems that maybe the ipc path has changed or it is unable to find it. I have done some investigation inside the container and don't see it either. The container was stable and working for the last 4 months, and just started having this issue today. When I run the scripts locally on Windows it works properly. I'm not sure where else to look.

**Comment by Hunter2807** [comment]
Seems like discord isn't installed on your laptop, is it?

**Comment by Jmarks199** [comment]
@Hunter2807 - It's running in a container, which has been working fine until today, and I have not changed anything. Perhaps something changed in the latest Discord .deb distribution or with a dependency. It's showing that I've successfully logged in to the GUI. But still getting the error above.

**Comment by Hunter2807** [comment]
Ah, can u try setting the pipe kwarg? Also go to the location of the file and see if the file is present there...

**Comment by Jmarks199** [comment]
Thanks for the advice. I ran the container with a GUI and found the issue. Even though I am pulling the .deb from the remote repository (wget "https://discord.com/api/download?platform=linux&format=deb"), upon launch it is throwing this screen which I have never seen before:

![image](https://user-images.githubusercontent.com/32776728/134553643-e2ee3826-a386-473d-a509-be5cd8ef45ed.png)
