### ISSUE TITLE
Allow values to be inline set to None/empty/whatever

### ISSUE THREAD

**Issue by Cynosphere** [qwertyquerty/pypresence#135]
```
pypresence.exceptions.ServerError: Child "activity" fails because child "assets" fails because child "large_text" fails because "large_text" is not allowed to be empty
```
This exception doesn't need to exist.

**Comment by Cynosphere** [comment]
And its extended to timestamps too.

**Comment by qwertyquerty** [comment]
This error is thrown by discord

**Comment by Cynosphere** [comment]
It works perfectly fine in other rich presences so it can't be being thrown by Discord. And it works fine leaving it out entirely, so it can't be the case.
