### ISSUE TITLE
Set ActivityType other than "Playing..."?

### ISSUE THREAD

**Issue by JakeGuy11** [qwertyquerty/pypresence#139]
[In this section of the Discord API docs](https://discord.com/developers/docs/game-sdk/activities#data-models), it says that you are able to set the ActivityType, but that it won't actually do anything and will be ignored by Discord. Is this still the case?

If not, is there a way to specify the ActivityType through this program?

**Comment by LewdNeko** [comment]
If the docs still say so then it's safe to assume that's the current behavior.
