### ISSUE TITLE
RPC queries don't update quickly enough

### ISSUE THREAD

**Issue by diamondburned** [qwertyquerty/pypresence#14]
Hey, I'm making an RPC script. Discovered this long ago, but even with `time.sleep(0.5)`, RPC still takes at least 10-15 seconds to update, which for my kind of game, is slow. Is there a way I can improve this?

**Comment by qwertyquerty** [comment]
Unfortunately, this is server side. Discord ratelimits how fast you can change your presence. You can only change it once every 15 seconds. This is not something I can fix without being a discord dev.

**Comment by qwertyquerty** [comment]
@diamondburned I thought I would also mention that pypresence can be installed with `pip install pypresence` now.

**Comment by diamondburned** [comment]
If queries are spammed, are they ignored/dropped or delayed?

**Comment by qwertyquerty** [comment]
@diamondburned currently, they are dropped, but in a future update I hope to have them delayed.

**Comment by diamondburned** [comment]
Well, for me it's great that they're dropped (short reason is because delayed packages will contain outdated information and my script runs in a loop)

**Comment by qwertyquerty** [comment]
@diamondburned It still is a bad idea to spam updates, it will eat up your CPU. Also perhaps there will be an option to turn on the delayed queue or not.

**Comment by diamondburned** [comment]
Sadly osu! on Linux doesn't really provide any method to send the info :( Maybe I'll try finding the sweet spot for `time.sleep()` though. Thanks.
