### ISSUE TITLE
Need Help - User clicked button don't take user to the website

### ISSUE THREAD

**Issue by dumb-stuff** [qwertyquerty/pypresence#142]

**Comment by GamingerYT** [comment]
i get tooo

**Comment by Hunter2807** [comment]
@GamingerYT and @dumb-stuff if u ain't in the support server, then pls join it and ping in me in pypresence channel. My username is Hunter in a different font, and I have the last message in that channel (;

I will be able to help you better there

**Comment by LewdNeko** [comment]
Insufficient information provided - feel free to reopen with a more complete issue.
