### ISSUE TITLE
update images

### ISSUE THREAD

**Issue by ResetXD** [qwertyquerty/pypresence#143]
i can't find docs on what large_image and small_image should be, is it a path? a url? or bytes? or the application avatar.
well i tried all but doesnt seem to get any image anyways.

please tell me what exactly to be used in those parameters. Also docs examples aint helping

**Comment by Hunter2807** [comment]
Those are the image names which u upload on the Discord Developer Portal in the Assets section.

**Comment by ResetXD** [comment]
ah
