### ISSUE TITLE
Getting error on Python 3.10

### ISSUE THREAD

**Issue by Dummerle** [qwertyquerty/pypresence#145]
With Python 3.10 i get the following error

>Traceback (most recent call last):
 > File "/home/lennard/presence.py", line 6, in <module>
 >   RPC.connect() # Start the handshake loop
>  File "/home/lennard/Coding/PycharmProjects/Rare/venv310/lib/python3.10/site-packages/pypresence/presence.py", line 43, in connect
>    self.loop.run_until_complete(self.handshake())
>  File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
>    return future.result()
>  File "/home/lennard/Coding/PycharmProjects/Rare/venv310/lib/python3.10/site-packages/pypresence/baseclient.py", line 128, in handshake
>    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
>  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
>    transport, _ = await loop.create_unix_connection(
>TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'

It works perfect with version 3.8 and 3.9

I tested the first example from https://qwertyquerty.github.io/pypresence/html/info/examples.html

OS: Arch Linux

**Comment by Hunter2807** [comment]
Ah, so this should be an easy fix. In Python 3.10, the loop parameter was removed from most of the methods/functions and that also includes create_unix_connection loop. So you will have to edit some internal files in order for this to work. 
-> Go to `/home/lennard/Coding/PycharmProjects/Rare/venv310/lib/python3.10/site-packages/pypresence/baseclient.py", line 128`
-> Remove the `loop=self.loop` arg from that function, including any trailing commas. 
-> Save the file and run your script again. It should work!

**Comment by Dummerle** [comment]
It works, thank you. Will there be an update to use it with pip?

**Comment by LewdNeko** [comment]
Yes
