### ISSUE TITLE
RPC not showing up on Discord

### ISSUE THREAD

**Issue by Mrgoldy-YT** [qwertyquerty/pypresence#146]
The issue I am having is when trying to see the RPC I have on Discord. It does not appear anywhere.
I am logged in on the Discord Developer Portal. I have an application created. Likewise, I have the correct client ID. The code successfully runs and works without errors. I do not have any empty arguments. 

What could be the problem?

As a side note, I am running Discord Canary. It should not cause any issues in a normal circumstance, however.

Now, I did some research as well. However, I could not fix it.

**Comment by LewdNeko** [comment]
I can't remember if this is still the case, but I seem to remember a weird quirk that prevents the person running their RPC from seeing their own status. Could you ask a friend to confirm if it does/doesn't display and if not post your code?

**Comment by Mrgoldy-YT** [comment]
Alright it works now, thank you for your help. It shows on my end as well.
