### ISSUE TITLE
pypresence.exceptions.ServerError: Secrets must be unique

### ISSUE THREAD

**Issue by RinkaGI** [qwertyquerty/pypresence#147]
hi, im doing a type of "library" with pypresence, when i run the richpresence, i get this error _pypresence.exceptions.ServerError: Secrets must be unique_ this is the file's code `from rpy import RichPresence, mantenerseActivo
from variables import *

rpc = RichPresence("829994723867492373")

rpc.añadir(
    estado="Playing Solo",
    detalles="Competitive",
    empiezaElTimestamp=tiempoDeEjecucion,
    terminaElTimestamp=tiempoDeEjecucion,
    imagenGrande="operagx",
    textoImagenGrande="Numbani",
    imagenPequeña="operagx",
    textoImagenPequeña="Rogue - Level 100",
    idPartida="ae488379-351d-4a4f-ad32-2b9b01c91657",
    tamañoPartida="1",
    tamañoMaximoPartida="5",
    partida="MTI4NzM0OjFpMmhuZToxMjMxMjM="
)

while True:
    mantenerseActivo(actualizarseCada=15)`
    
    the "library"'s code is this: `from pypresence import *
import time

bucle = True

class RichPresence(Presence):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.connect()

    def conectar(self):
        self.connect()

    # Funciones para añadir cosas
    def añadir(self,
     estado: str = None,
     detalles: str = None,
     empiezaElTimestamp: int = None, 
     terminaElTimestamp: int = None, 
     imagenGrande: str = None, 
     textoImagenGrande: str = None,
     imagenPequeña: str = None,
     textoImagenPequeña: str = None,
     idPartida: str = None,
     tamañoPartida: int = None,
     tamañoMaximoPartida: int = None,
     entrar: str = None,
     espectear: str = None,
     partida: str = None,
     botones: list = None,
     instancia: bool = True):
        self.update(
            
            state=str(estado),
            details=str(detalles),
            start=int(empiezaElTimestamp),
            end=int(terminaElTimestamp),
            large_image=str(imagenGrande),
            large_text=str(textoImagenGrande),
            small_image=str(imagenPequeña),
            small_text=str(textoImagenPequeña),
            party_id=str(idPartida),
            party_size=[int(tamañoPartida), int(tamañoMaximoPartida)],
            join=str(entrar),
            spectate=str(espectear),
            match=str(partida),
            buttons=botones,
            instance=bool(instancia)
            )
        return

def mantenerseActivo(actualizarseCada):
    time.sleep(int(actualizarseCada))`
    
    and in variables's code there's the variable: "tiempoDeEjecucion" that is "time.time()"
    
    srry if i have bad english

**Comment by Hunter2807** [comment]
Yo bruv, join the discord server and we will be able to help you better @RinkaGI

**Comment by LewdNeko** [comment]
Could you please run your script in a debugger and find out where exactly this error is happening. As much traceback as possible and we'll be able to help best.

**Comment by LewdNeko** [comment]
Closing: Resolved in Discord.

Match, Spectate, and Join must be unique strings.
