### ISSUE TITLE
No errors but still not working

### ISSUE THREAD

**Issue by batsoup804** [qwertyquerty/pypresence#152]
So I'm using local python with normal discord installed. I'm using python 3.9 in visual studio code. I've copy-pasted the code from the quick-start guide in your documentation and still nothing. When I check my discord all it has is the visual studio code status. 
![image](https://user-images.githubusercontent.com/83473782/141662079-ac6bfeb1-8a55-4f2d-b30e-79380ab36c26.png)
this is my EXACT code (but with my client ID) and here's what my discord looks like when run- 
![image](https://user-images.githubusercontent.com/83473782/141662117-55e367ea-330a-4392-985f-5b53d30bfd97.png)
Tried every tutorial on youtube and nothing works. please help.

**Comment by LewdNeko** [comment]
Close visual studio

**Comment by batsoup804** [comment]
Fixed. Ran my program from the command line and it is working fine. Thank you!
