### ISSUE TITLE
Support for the new type field

### ISSUE THREAD

**Issue by B34rly** [qwertyquerty/pypresence#155]
Discord added a new rpc field, 'type', could it be added to a pypresence update?
[new field documentation](https://discord.com/developers/docs/topics/gateway#activity-object-activity-types)

**Comment by Hunter2807** [comment]
Sure, ig. Imma try adding it but will still want anyone to test it since, uhhh, I use Discord Web 😶

**Comment by B34rly** [comment]
I'm fine to test it if you need me to

**Comment by LewdNeko** [comment]
After some discussion in Discord, there is currently no information on this feature that leads to having anything other than "Playing"
