### ISSUE TITLE
update() got an unexpected keyword argument 'buttons'

### ISSUE THREAD

**Issue by CDAGaming** [qwertyquerty/pypresence#159]
As the title says, I've been getting this weird issue lately with an implementation I had made using pypresence.
No recent edits have been made to it in the past, so I'm confused as to why this issue is suddenly appearing

**Comment by Hunter2807** [comment]
@CDAGaming Update your pypresence by `pip install -U pypresence`

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/152696765-61a54757-e39c-4c49-b72e-d1fe1c0fe8b1.png)
Already is up to date

**Comment by Hunter2807** [comment]
Mind sharing some code?

**Comment by CDAGaming** [comment]
Sure thing, all files of importance are at https://gitlab.com/CDAGaming/CraftPresence-Wow-Edition/-/tree/master/Script

**Comment by Hunter2807** [comment]
Okay, so what I want you to do here is, you should join the official Discord server so that we can solve this issue faster

**Comment by qwertyquerty** [comment]
You're probably on an old version of the lib, update

**Comment by CDAGaming** [comment]
Resolved
