### ISSUE TITLE
Exception ignored from asyncio

### ISSUE THREAD

**Issue by ConaII** [qwertyquerty/pypresence#168]
If discord is closed/crashes while RPC.connect(), this ignored error will print:
![image](https://user-images.githubusercontent.com/72966048/170849475-93d92b59-46ee-4593-9cc6-0605abb29f7a.png)

Normally this is not reproducible unless you're very unlucky or damm fast, but if it get's stuck trying to connect, this is much easier to replicate

**Comment by ConaII** [comment]
I tried to find anything inside this repo but I don't see any problems so I don't know
I would like to hide it but i can't find a way.

**Comment by pogrammar** [comment]
Can you send the code?

**Comment by ConaII** [comment]
```
def rpcLoop(RPC):
    from pypresence import InvalidPipe, InvalidID
    from time import sleep, time
    start_time = time()
    RPCbuttons = [{"label" : "Download Wood", "url" : "https://github.com/giganlak/wood"}, {"label" : "Join the Discord Server", "url" : "https://discord.gg/NdpXhhSDRP"}]
    while True:
        try:
            RPC.update(details=getSentence(_vars.room), state=f'Current money: {_vars.var["money"]}', large_image='wood1024', large_text=f'Total playtime: {timeConvert()[:-2]}', start=start_time, buttons=RPCbuttons)
            sleep(3)
        except(InvalidPipe, InvalidID):
            return

def RPCStart():
    from pypresence import Presence, DiscordNotFound
    from threading import Thread
    client_id = "000000000000000000" # (hidden)
    try:
        RPC = Presence(client_id)
    except DiscordNotFound:
        return
    try:
        RPC.connect()
    except (ValueError, Exception):
        return

    RPC_Thread = Thread(target=rpcLoop, args=(RPC, ), daemon=True)
    RPC_Thread.start()
```

**Comment by ConaII** [comment]
All our current problems are related to RPC.connect()
Sometimes it just gets stuck and doesn't want to continue.
I tried to connect inside a thread but i only got more errors

**Comment by Hunter2809** [comment]
That is not an issue with the library. It can be fixed by passing the `handler` kwarg in the `Presence` class' init

**Comment by ConaII** [comment]
Oh, sorry i'll try that.

**Comment by ConaII** [comment]
```
Traceback (most recent call last):
  File "utils\alt_funcs.py", line 690, in RPCStart
    RPC = Presence(client_id, handler=errorHandler)
  
  File "python38\site-packages\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "python38\site-packages\pypresence\baseclient.py", line 57, in __init__
    loop.set_exception_handler(err_handler)
AttributeError: 'NoneType' object has no attribute 'set_exception_handler'

[proccess ended with exit code 1 (0x00000001)]
```

**Comment by ConaII** [comment]
![image](https://user-images.githubusercontent.com/72966048/170889177-f7adcc67-1c63-4670-a08c-0ed22a189103.png)

Sometimes this error raises (when discord is closed?, idk why it happens but it's kinda rare), and it's not handled in here.
https://github.com/qwertyquerty/pypresence/blob/4fc19b14284d87e2e02ea57c74722ee9a4ff20e3/pypresence/baseclient.py#L82

**Comment by ConaII** [comment]
I moved unrelated issues to this post.
