### ISSUE TITLE
Loop is NoneType when adding errorHandler to Presence()

### ISSUE THREAD

**Issue by LcyDev** [qwertyquerty/pypresence#169]
```
Traceback (most recent call last):
  File "utils\alt_funcs.py", line 690, in RPCStart
    RPC = Presence(client_id, handler=errorHandler)
  
  File "python38\site-packages\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "python38\site-packages\pypresence\baseclient.py", line 57, in __init__
    loop.set_exception_handler(err_handler)
AttributeError: 'NoneType' object has no attribute 'set_exception_handler'

[proccess ended with exit code 1 (0x00000001)]
```
This happens when you parse a handler through Presence() and you don't supply loop argument.
This can be fixed using:
```
RPC = Presence(client_id, loop=get_event_loop(), handler=errorHandler)
```

It seems loop becomes None for some reason, even though docs say 
"loop (asyncio.BaseEventLoop) – Your own event loop (if you have one) that PyPresence should use. One will be created if not supplied"

https://github.com/qwertyquerty/pypresence/blob/4fc19b14284d87e2e02ea57c74722ee9a4ff20e3/pypresence/baseclient.py#L30-L33

**Comment by Hunter2809** [comment]
#193 was merged regarding the issue. Please check if your issue was fixed and post any update(s)

**Comment by LcyDev** [comment]
This was fixed!
