### ISSUE TITLE
External images with rich presence using image proxy.

### ISSUE THREAD

**Issue by FireHead90544** [qwertyquerty/pypresence#177]
**Hello There!**
Is there any way to use any external image url instead of the asset key registered in the developer portal?

There is something written in brief about it in the docs.
![image](https://user-images.githubusercontent.com/55452780/185892970-9cefe2d4-4c04-433d-99ce-f12feb3f9982.png)

I've seen a similar post on reddit mentioning this. 
![image](https://user-images.githubusercontent.com/55452780/185893455-ef350471-380d-4587-9ba2-16fe55f8d3c5.png)
[Source](https://www.reddit.com/r/discordapp/comments/rndazc/discord_finally_enabled_the_ability_to_load_rich/)

But sadgely, that's a JS implementation of it, I've tried doing the same with pypresence, but the images aren't being shown.
Am I going anywhere wrong? Any help would be appreciated. 
Thank You.

**Comment by Hunter2809** [comment]
Hi @FireHead90544! 

This feature is already implemented in pypresence. Please join the support server to get faster help with this thing. 
Cheers!

**Comment by FireHead90544** [comment]
Oh my bad, I'll join. Great Thanks 👍

**Comment by FireHead90544** [comment]
Nvm, I found the simple fix myself. You can indeed use an image url in place of asset's keys. But you need to make sure that the url has a public access (accessible by everyone). Make sure to include the filetype (.png, .jpg, etc. in the url)
