### ISSUE TITLE
Pip version is outdated

### ISSUE THREAD

**Issue by Modelmat** [qwertyquerty/pypresence#18]
The version downloaded off pip is outdated; it needs to be updated to latest version. (the docs don't mention this)

**Comment by LewdNeko** [comment]
Can't update ppypi myself, so just install with `pip install https://github.com/qwertyquerty/pypresence/archive/master.zip` for now. Will get qwerty to update pypi when he's back.

**Comment by LewdNeko** [comment]
It has been updated now. 1.0.7 is on pypi.
