### ISSUE TITLE
[Question] How would you handle timeouts?

### ISSUE THREAD

**Issue by Lezalith** [qwertyquerty/pypresence#182]
If I understand correctly, triggering `Presence.connect` multiple times in quick succession, the Application will refuse the connection, and the function keeps on trying until it succeeds.

Would there be some kind of exception that would detect this, so that it stops trying to connect and other code can be run?

**Comment by NikOverflow** [comment]
> If I understand correctly, triggering `Presence.connect` multiple times in quick succession, the Application will refuse the connection, and the function keeps on trying until it succeeds.
> 
> Would there be some kind of exception that would detect this, so that it stops trying to connect and other code can be run?



> If I understand correctly, triggering `Presence.connect` multiple times in quick succession, the Application will refuse the connection, and the function keeps on trying until it succeeds.
> 
> Would there be some kind of exception that would detect this, so that it stops trying to connect and other code can be run?

do it every 15 seconds and everything is fine. (The rate limit is 15 seconds)

**Comment by NikOverflow** [comment]
> If I understand correctly, triggering `Presence.connect` multiple times in quick succession, the Application will refuse the connection, and the function keeps on trying until it succeeds.
> 
> Would there be some kind of exception that would detect this, so that it stops trying to connect and other code can be run?

What you can do is: Every 15 seconds you call the update method and if it throws an exception then the connection died.

**Comment by NikOverflow** [comment]
i explain that to you.

**Comment by NikOverflow** [comment]
I hope this is helpful. If not you can open that issue again.
