### ISSUE TITLE
Connection seems to work fine but updating doesn't

### ISSUE THREAD

**Issue by s-mick** [qwertyquerty/pypresence#19]
## Issue description

When trying to update the status, I get an "Unknown error" message in the server's response, which looks like this:
```
{'cmd': 'SET_ACTIVITY', 'data': {'code': 1000, 'message': 'Unknown Error'}, 'evt': 'ERROR', 'nonce': '1525529333.90793704986572265625'}
```
and `read_output()` raises a `ServerError` exception 

## Observations

The connection step before that (`Presence.connect()`) seems to work just fine, as I get this response from the server:
```
{'cmd': 'DISPATCH', 'data': {'v': 1, 'config': {'cdn_host': 'cdn.discordapp.com', 'api_endpoint': '//discordapp.com/api', 'environment': 'production'}, 'user': {'id': 'XXXX', 'username': 'XXXX', 'discriminator': 'XXXX', 'avatar': 'XXXX', 'bot': False}}, 'evt': 'READY', 'nonce': None}
```
with my correct user info (in place of the XXXX), suggesting that this part is OK.

## Reproduction

I first encountered this issue when running the `rich-presence.py` example, but it similarly happens with any other script where the `Presence.update()` method is used.

## System info

* pypresence 2.0.0 downloaded from the GitHub repo and installed with `pip install .`
* Python 3.6.5 installed with Homebrew
* OS X 10.11.6.

**Comment by qwertyquerty** [comment]
This is rather odd, make sure you arent being ratelimited, (I assume you aren't) but I'll have to look into this myself. @s-mick

Did you change any of the code in the examples before you ran?

**Comment by s-mick** [comment]
What do you mean by "ratelimited"?

No, I didn't change the code. I fiddled with the package's source code in order to get the contents of the server's response, but the error was already happening before I changed anything to it.

**Comment by s-mick** [comment]
I solved my issue: my app wasn't properly registered to manage rich presence features. It's a pity that the error message didn't mention it in the server's response…
