### ISSUE TITLE
AttributeError: 'Presence' object has no attribute 'Update'

### ISSUE THREAD

**Issue by diamondburned** [qwertyquerty/pypresence#20]
Hey. Fixing my `osu-linux-rpc` code, but I met some trouble from release `1.1.0`:

    Traceback (most recent call last):
      File "osu-linux-rpc.py", line 22, in <module>
        RPC.Update(details=full, state=info, large_image="osu-large", large_text="Linux is better", small_image="wine", small_text=winever)
    AttributeError: 'Presence' object has no attribute 'Update'

I did `from presence import Presence` and 

    client_id = 'id' # My ID, please no abuse :(
    RPC = Presence(client_id)
    RPC.connect() # Magic PyPresence stuff, no idea :(

but that doesn't seem to be the problem here.

The only thing I modified is this part:

    from exceptions import *
    from utils import *

since I have the script stored locally instead of in the system. The 2 files are still there, untouched.

Oh yea, just want to mention, I import the `pypresence.py` file, not `client.py` file. Kind of confused on which file to use, as `client.py`'s syntax seems to differ from the examples.

**Comment by qwertyquerty** [comment]
Presence.**U**pdate should be lowercase m'boy.

**Comment by diamondburned** [comment]
oh so it's `Presence.Update()` and not `RPC.Update()`? Forgive me I just followed the examples without really double-checking the codes

**Comment by qwertyquerty** [comment]
Should be this:

```python
RPC.update(details=full, state=info, large_image="osu-large", large_text="Linux is better", small_image="wine", small_text=winever)
```

**Comment by diamondburned** [comment]
Thanks. I assume it's safe to close this now. I've stumbled upon yet another problem, but I'll open another issue.
