### ISSUE TITLE
No releases since Nov 21, 2021

### ISSUE THREAD

**Issue by Dliwk** [qwertyquerty/pypresence#224]
Any reason why pypresence 4.3/5.0 has not been released yet? This repository contains important fixes (ex: #203), which aren't available from PyPI. :disappointed:

**Comment by qwertyquerty** [comment]
I've left this project unmaintained for a while but am coming back to it for a bit now, v4.3.0 released

**Comment by C0rn3j** [comment]
Would it be possible to have a new release?

It's been a while again, and the activity type support is gated behind master at the moment.
