### ISSUE TITLE
A way to close RPC without stopping the Python loop

### ISSUE THREAD

**Issue by diamondburned** [qwertyquerty/pypresence#23]
Kind of funny how I asked the opposite a month ago. 

In my script, I have a loop script to check whether the window is open or not. I need it so that if it's not open, close the RPC connection and keep checking. I've tried `RPC.close()`, but that returns

    Traceback (most recent call last):
      File "./gimp-rpc.py", line 56, in <module>
        print(RPC.update(details=line1, state=line2, large_image="gimp-papirus", large_text=version))
      File "/home/diamond/Scripts/gimp-rpc/presence.py", line 122, in update
        return self.loop.run_until_complete(self.read_output())
      File "/usr/lib/python3.6/asyncio/base_events.py", line 444, in run_until_complete
        self._check_closed()
      File "/usr/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
        raise RuntimeError('Event loop is closed')
    RuntimeError: Event loop is closed

Script is basically if Bash file (yes, laugh) returns blank, run RPC loop, if it's no longer blank, recheck the Bash file until it's blank again, then initiate the RPC loop. I want to stop the RPC connection at the part where it rechecks the Bash file. Script if it helps you: https://hastebin.com/qucekelowo.py

**Comment by qwertyquerty** [comment]
If you simply want to clear the presence use `RPC.clear ()`

**Comment by qwertyquerty** [comment]
Also bash... ha 
ha
 ha
 ha
 ha 
ha 
ha
 ha

**Comment by diamondburned** [comment]
Worked. I just had to update PyPresence :eyes:
