### ISSUE TITLE
Running when Discord is not open

### ISSUE THREAD

**Issue by Ax1rc** [qwertyquerty/pypresence#241]
Hello, I was wondering if it possible to make it so my program will still run if Discord is not open, just without the RPC. I tried using try and except as shown in the image below but it did not work. The other image shows that my game will not run if Discord is not open. Thank you!

![Screenshot 2024-06-05 214926](https://github.com/qwertyquerty/pypresence/assets/104878465/c098f9e7-88cd-407d-bf1e-d988d04da2f4)
![Screenshot 2024-06-05 215053](https://github.com/qwertyquerty/pypresence/assets/104878465/72e19d10-9d69-4dd0-a879-701dadfc72fc)

**Comment by NikOverflow** [comment]
> Hello, I was wondering if it possible to make it so my program will still run if Discord is not open, just without the RPC. I tried using try and except as shown in the image below but it did not work. The other image shows that my game will not run if Discord is not open. Thank you!
> 
> ![Screenshot 2024-06-05 214926](https://private-user-images.githubusercontent.com/104878465/337116304-c098f9e7-88cd-407d-bf1e-d988d04da2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk4ODgsIm5iZiI6MTcxNzY0OTU4OCwicGF0aCI6Ii8xMDQ4Nzg0NjUvMzM3MTE2MzA0LWMwOThmOWU3LTg4Y2QtNDA3ZC1iZjFlLWQ5ODhkMDRkYTJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzY1MDQ0MmIxYjBhNzQ5NzY1MDA1NjYzNzg1MjczYzIyNTU3MjhkYmJjMTM2YjhkNTMwYjFhMDNmYzcwMGJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z6AjmTYUWkdGEN77JKYVksevli9DSePXAPyetNZTV0o) ![Screenshot 2024-06-05 215053](https://private-user-images.githubusercontent.com/104878465/337116319-72e19d10-9d69-4dd0-a879-701dadfc72fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDk4ODgsIm5iZiI6MTcxNzY0OTU4OCwicGF0aCI6Ii8xMDQ4Nzg0NjUvMzM3MTE2MzE5LTcyZTE5ZDEwLTlkNjktNGRkMC1hODc5LTcwMWRhZGZjNzJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNDUzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzMyZWQ2OGVlZWExYmU1ZjMwMmE0MjBjN2YzMDM2MzQ3NDliZTM5NTA0M2E5ZTI2NTlkYTBmMGVhN2Q5YmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6gBiI6Z1aWLNm25sPNZbnv8cV9hNxv3gkfDNRqjCxpY)

I did it like this https://github.com/SecSchool/discord-rich-presence/blob/master/src/main.py

**Comment by Ax1rc** [comment]
wait actually I was able to fix it just now! ty for helping tho

**Comment by Ax1rc** [comment]
turns out it did work if I used try except lmaoo
