### ISSUE TITLE
no buttons

### ISSUE THREAD

**Issue by FozerG** [qwertyquerty/pypresence#243]
Discord broke something again and the buttons are gone. Any information?

**Comment by perites** [comment]
same issue, buttons just gone

**Comment by vRefilv** [comment]
only for python tho
![image1](https://github.com/qwertyquerty/pypresence/assets/53364591/fcba2d49-701f-4ba9-85df-b788e088f171)
![image](https://github.com/qwertyquerty/pypresence/assets/53364591/3b066be6-de9f-4d65-8fee-7bde5bc4fc62)

**Comment by FozerG** [comment]
what do you mean? How did you get the buttons?

> only for python tho ![image1](https://private-user-images.githubusercontent.com/53364591/344736322-fcba2d49-701f-4ba9-85df-b788e088f171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NjYxNTEsIm5iZiI6MTcxOTg2NTg1MSwicGF0aCI6Ii81MzM2NDU5MS8zNDQ3MzYzMjItZmNiYTJkNDktNzAxZi00YmE5LTg1ZGYtYjc4OGUwODhmMTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZmQ3ZTkyNmQ3OWM3M2U1YTM1NGU2MTQyZGE3OGUzZjA3MTFjMTYzMTFlYTZhNDM3Y2QzYTU4ODc5MDE2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V7Q9WQuFeX5Qb-chiFsLk5bWDPdeAffk1RH0EgpCzW4) ![image](https://private-user-images.githubusercontent.com/53364591/344736329-3b066be6-de9f-4d65-8fee-7bde5bc4fc62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NjYxNTEsIm5iZiI6MTcxOTg2NTg1MSwicGF0aCI6Ii81MzM2NDU5MS8zNDQ3MzYzMjktM2IwNjZiZTYtZGU5Zi00ZDY1LThmZWUtN2JkZTViYzRmYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIwMzA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMWYzNmI4ZjdmNjcyZTA4MGI3YjIyODY0OTMyNGNkYzU1OTYwOGY3MjE4N2ZlNGJlOTc0ZWQ4YjI5MGRhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y9QBSRPm0g0noDTDza3b0Cnrkj88sPCm9ty0As0QeeY)

**Comment by vRefilv** [comment]
i mean that buttons are removed only in python discord api other programming languages normally have buttons,and every python module dont have buttons. skill issue

**Comment by LeaLangley** [comment]
its a issue from the new profile appearance , the buttons are visible for others but not for yourself , for some reason.

**Comment by PrajwalVandana** [comment]
I think Discord's phasing them out 😔

**Comment by NikOverflow** [comment]
This is only for the person who starts the rich presence. The others can see the buttons, so it's more of a Discord thing.
