### ISSUE TITLE
Script fails on 3.5.3

### ISSUE THREAD

**Issue by diamondburned** [qwertyquerty/pypresence#25]
`python --version` returns 3.5.3

	Traceback (most recent call last):
	  File "rich.py", line 2, in <module>
	    from presence import Presence
	  File "/home/richpresence/presence.py", line 47
	    self.sock_reader: asyncio.StreamReader = None
	                    ^
	SyntaxError: invalid syntax

**Comment by LewdNeko** [comment]
Ah, yes. Have you always had this issue? I don't think anyone else has on Python < 3.6

**Comment by LewdNeko** [comment]
Could you try updating everything on that system and seeing if it fixes anything? Python 3.6+ is recommended by the way.

**Comment by qwertyquerty** [comment]
This will be fixed ASAP

**Comment by LewdNeko** [comment]
Does this still happen? Qwerty is useless. @diamondburned

**Comment by qwertyquerty** [comment]
This should now be fixed in 3.1
