### ISSUE TITLE
add a travis ci build

### ISSUE THREAD

**Issue by kot83** [qwertyquerty/pypresence#26]
and a fancy badge on the readme

**Comment by LewdNeko** [comment]
What is a Travis CI Build?

**Comment by kot83** [comment]
google it

**Comment by kot83** [comment]
https://travis-ci.org/

**Comment by LewdNeko** [comment]
I see no benefit from this & don't think it will let me as I don't own the repo.

**Comment by kot83** [comment]
With a ci build we could validate prs and see if the package actually builds

**Comment by LewdNeko** [comment]
We don't receieve enough PRs to make it worth the effort.

**Comment by qwertyquerty** [comment]
un-needed
