### ISSUE TITLE
[Suggestion] Event Loop kwarg

### ISSUE THREAD

**Issue by xKynn** [qwertyquerty/pypresence#28]
Hi, Great RPC Client btw!
Just wanted to know if you would consider adding a kwarg for people to be able to pass their own established event loop as a kwarg?
I made a shoddy patch on my project at https://github.com/xKynn/PathOfExileRPC to use it that way, though in hindsight i think I could've just initialized the Presence object before my own and pass the loop in from there to my class

**Comment by LewdNeko** [comment]
Will add in next update. Thanks for the idea :)

**Comment by qwertyquerty** [comment]
Sounds like something that could be done

**Comment by LewdNeko** [comment]
Patch has been released to GH. Will be pushed to PyPi soon.

**Comment by xKynn** [comment]
That's great, thanks and good luck!
