### ISSUE TITLE
How to set image of the game ?

### ISSUE THREAD

**Issue by Ekansh-kashyap** [qwertyquerty/pypresence#30]
I'm unable to set the image of the game and yeah I read the docs before asking.

**Comment by LewdNeko** [comment]
"Unable to do it" is too vague. What have uou tried and what was the error? The library has been fully fested and works as it should.

**Comment by LewdNeko** [comment]
Will close in 3 days if no reply, @Ekansh-kashyap

**Comment by Ekansh-kashyap** [comment]
Idk the syntax for doing it.

**Comment by Ekansh-kashyap** [comment]
Ohk Got it.
