### ISSUE TITLE
excepting InvalidPipe

### ISSUE THREAD

**Issue by xKynn** [qwertyquerty/pypresence#31]
```py
        try:
            self.rpc.connect()
        except InvalidPipe:
            logger.info("Discord not open, waiting for discord to launch...")
            while 1:
                try:
                    self.rpc.connect()
                    break
                except InvalidPipe:
                    pass
                await asyncio.sleep(5)
```
This is something I'm trying to do, while with a wide except of something like Exception, I am able to make it work, it still outputs Task exception never received in the console which i think is not something i can catch/except only on `connect`.
PS. I wonder if this would work if connect was changed to a coro and then handshake was called with await?

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Presence.handshake() done, defined at I:\pypresence\presence.py:55> exception=InvalidPipe('Pipe Not Found - Is Discord Running?',)>
Traceback (most recent call last):
  File "I:\pypresence\presence.py", line 64, in handshake
    self.sock_writer, _ = yield from self.loop.create_pipe_connection(lambda: reader_protocol, self.ipc_path)
  File "C:\Python\Python36\lib\asyncio\windows_events.py", line 317, in create_pipe_connection
    pipe = yield from f
  File "C:\Python\Python36\lib\asyncio\windows_events.py", line 547, in connect_pipe
    handle = _overlapped.ConnectPipe(address)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\pypresence\presence.py", line 66, in handshake
    raise InvalidPipe
pypresence.exceptions.InvalidPipe: Pipe Not Found - Is Discord Running?
```

**Comment by LewdNeko** [comment]
I cannot fully review the issue at the moment, but can reply to your PS. We do not have connect as a coro due to people using this library synchronously - we get the event loop on our own so that it is as easy as possible to use.

**Comment by xKynn** [comment]
This is actually a non issue i will close after posting this, as a big facepalm, I forgot to compile with cx_freeze before testing, apologies.

**Comment by xKynn** [comment]
Actually, still isn't fixed, I'll wait on you guys

**Comment by xKynn** [comment]
So yeah, can confirm patching it to work in await context lets me except invalidpipe, as for possible solutions for this out of the box, I can't think of something elegant, possible a separate async_connect method, which would work but feels very un-neat to me

**Comment by LewdNeko** [comment]
Is your logger set to debug? I'm pretty sure it's just asyncio logging.

**Comment by xKynn** [comment]
Logger's set to info

**Comment by LewdNeko** [comment]
I'm working on allowing for users to pass their own function as an exception handler, hopefully this will fix it.

**Comment by LewdNeko** [comment]
Could you install pypresence from `pip install https://github.com/qwertyquerty/pypresence/archive/master.zip` and try passing your own function as the error handler (`RPC = Presence(client_id, handler=yourfunctionobject)`)? Hopefully this will fix the problem.

**Comment by LewdNeko** [comment]
No reply from OP, closing. Feel free to re-open :)
