### ISSUE TITLE
Issues with start time

### ISSUE THREAD

**Issue by GhostofGoes** [qwertyquerty/pypresence#32]
Running into some issues with the `start` parameter in `client.update()`. What we want is for the time to start from when the update is issued, however, that doesn't seem to be possible.

If set to `0`, the following error occurs:
```python
pypresence.exceptions.ServerError: Child "activity" fails because child "timestamps" fails
 because child "start" fails because "start" must be larger than or equal to 1
```
If set to `1`, the "start" time gets set to ~5 hours, which is definitely not what I expected. Example: [https://imgur.com/6vp9RMf](https://imgur.com/6vp9RMf)

Example code:
```python
from pypresence import Presence
import time

# PUT A TEST CLIENT ID HERE
client_id = ''

RPC = Presence(client_id)
RPC.connect()

start_time = 1
print(RPC.update(state="No important DMs please", details="Trying to sleep", start=start_time,
                 large_image="monoblobsleep", large_text="Sleeping. Please no DMs",
                 join="MTI4NzM0OjFpMmhuZToxMjMxMjM="))
while True: 
    time.sleep(15)

**Comment by qwertyquerty** [comment]
`int(time.time())`*

**Comment by GhostofGoes** [comment]
`int(time.time())` worked. Should've read the documentation closer, since `epoch seconds for game start` is epoch as in the Unix epoch.

Thanks neko and qwerty! 😄

**Comment by xman213** [comment]
Replace start=start_time with start=time.time( )
