### ISSUE TITLE
Error installing the module

### ISSUE THREAD

**Issue by ndr3w221** [qwertyquerty/pypresence#34]
This is what I get when I install pypresence (`pip install pypresence`):
```Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0rsa25u1/pypresence/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hn2y1230/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-0rsa25u1/pypresence/```

**Comment by cheddar-cheeze** [comment]
Im having issues as well ,though mine is due to a syntax error 
`byte-compiling build/bdist.linux-x86_64/egg/pypresence/utils.py to utils.cpython-37.pyc
  File "build/bdist.linux-x86_64/egg/pypresence/utils.py", line 20
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
`
and the pip package does not seem to be up to date with the repo module

**Comment by LewdNeko** [comment]
@cheddar-cheeze I'm going to push the latest fixes to PyPi within the next 10 minutes. I will edit my post once it's done. In the meantime, if you really can't wait, install vai `pip install https://github.com/qwertyquerty/pypresence/archive/master.zip`

**Comment by LewdNeko** [comment]
@ndr3w221 I think this a permission error. Try `sudo pip install pypypresence` or setup a virtualenv and install it to there. If not, let me know.

**Comment by GhostofGoes** [comment]
You can also try `python -m pip install --user pypresence`

**Comment by ndr3w221** [comment]
thanks @GhostofGoes it worked!
