### ISSUE TITLE
How do I use?

### ISSUE THREAD

**Issue by Alej0hio** [qwertyquerty/pypresence#41]
I know python and all, but the documentation isn't helping alot.
Do I need to use async? Please make a tutorial, this is really not helping out and pretty bad documentation overall.

**Comment by LewdNeko** [comment]
There are fully working examples at the following link: https://github.com/qwertyquerty/pypresence/blob/master/examples/rich-presence.py

**Comment by qwertyquerty** [comment]
@Alej0hio How dare you insult my docs. I spent hours and hours of work on those. They are in fact the best docs I myself have ever seen.
