### ISSUE TITLE
SyntaxError: invalid syntax on Python 2.7

### ISSUE THREAD

**Issue by MDTech-us-MAN** [qwertyquerty/pypresence#53]
Error when running the example on python 2.7.

```
$ python rich-presence.py 
Traceback (most recent call last):
  File "rich-presence.py", line 1, in <module>
    from pypresence import Presence
  File "build/bdist.linux-x86_64/egg/pypresence/__init__.py", line 7, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pypresence-3.2.2-py2.7.egg/pypresence/activity.py", line 12
    def __init__(self, client: Presence, pid: int = os.getpid(),
                             ^
SyntaxError: invalid syntax
```

**Comment by qwertyquerty** [comment]
Y I K E S. We do not support python 2. You very much so need to update python versions. We support 3.5-7

**Comment by MDTech-us-MAN** [comment]
I'm supporting a very old massive game so it will be VERY complicated to upgrade.  -_-

Oh well... thanks anyways.

**Comment by qwertyquerty** [comment]
What game?

**Comment by MDTech-us-MAN** [comment]
Toontown Fellowship. Its a revival of an old Disney game.

**Comment by MDTech-us-MAN** [comment]
It's OK. I managed to find another much more basic library that I could backport and make it work to my needs.

**Comment by qwertyquerty** [comment]
What library? I might look at it to see if we could make a python 2 branch

**Comment by theclashingfritz** [comment]
Toontown Fellowship is not massive. If it was Toontown Rewritten maybe. But not Fellowship. Don't say massive if it isn't massive.

**Comment by theclashingfritz** [comment]
Also nice project.
