### ISSUE TITLE
Joining Example

### ISSUE THREAD

**Issue by mitgobla** [qwertyquerty/pypresence#58]
Not sure if this is the best place to ask this, but do you have an example that utilizes the Client() method that can take player requests to join the game?

**Comment by LewdNeko** [comment]
No.

**Comment by mitgobla** [comment]
Ah no worries, I'll do some more digging to get a version working based off the Discord docs. Thanks 😄

**Comment by LewdNeko** [comment]
Cheeck examples folder.
