### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 12944qwerty** [qwertyquerty/pypresence#65]
I've tried to use this but nothing shows up on discord. I've tried the examples (copy and paste) but it still doesn't work.

Also, can you add a usage section in the documentation? It's really confusing without it.

**Comment by qwertyquerty** [comment]
Can you send the exact code you are using?

**Comment by qwertyquerty** [comment]
As well as python version, discord standard or canary?

**Comment by LewdNeko** [comment]
Fucking most uninformative, useless, and shitty issue ever mode. Please learn how to create an issue that allows people to **actually help you**, rather than let them grasp at straws from little to no information.

**Comment by 12944qwerty** [comment]
sorry......

I'm using repl........... - [repl.it](https://repl.it/@12944qwerty/Ratchet?language=python3&folderId=) Also, python3.6.1

I don't get what you mean by discord Canary of standard.

**Comment by LewdNeko** [comment]
My CoDe DoEsNt WoRk On RePl. Please don't even bother trying to create Discord RPC. Sorry, you're about 12 and it's clearly out of your depth. Retry in a couple years 😸

**Comment by 12944qwerty** [comment]
I'm 14............... :cry:

**Comment by LewdNeko** [comment]
oohhhh yeah rip you then.

multiple things

a) "whats discord canary" big RIp. you nyeed to understand more about Discord before touching bots or the RPC.
b) You have blocking code which will stop the presence code from even running
c) It won't work anyway. It needs to be running on a machine that HAS DISCORD INSTALLED.

**Comment by 12944qwerty** [comment]
a) I'll ask someone
b) blocking code?
c) :cry:

**Comment by LewdNeko** [comment]
not just discord canary. discord IN GENERAL. Sorry. Stop.

**Comment by 12944qwerty** [comment]
What do u mean that I have 'blocking code'?

**Comment by LewdNeko** [comment]
![image](https://user-images.githubusercontent.com/24483290/53752225-00c64d80-3ea6-11e9-823a-7dff8b75f01a.png)

**Comment by 12944qwerty** [comment]
Idk what u r talking about.... I very confuzled

**Comment by qwertyquerty** [comment]
@12944qwerty sorry for Neko's temper, what he means is:

You must run the code on a machine that has Discord installed. repl.it won't work because it actually runs the code on a far away server, and not actually on your computer, and just sends you the output.

Discord Canary is like a beta version of Discord, if you're not using it, don't worry about it.

You might like the [Quickstart](https://qwertyquerty.github.io/pypresence/html/info/quickstart.html) page of our docs

**Comment by 12944qwerty** [comment]
Ah, thanks! (fellow qwertyian)
