### ISSUE TITLE
If i closing RPC terminal typing me error.

### ISSUE THREAD

**Issue by Arny4** [qwertyquerty/pypresence#66]
If i closing RPC terminal typing me this error:
`Traceback (most recent call last):
  File "startgui.pyw", line 79, in StopRPC
    RPC.close()
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypresence\presence.py", line 43, in close
    self.send_data(2, {'v': 1, 'client_id': self.client_id})
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypresence\baseclient.py", line 93, in send_data
    self.sock_writer.write(
AttributeError: 'NoneType' object has no attribute 'write'`
Python version 3.6.8 .

**Comment by Arny4** [comment]
Will I ever wait for an answer? @qwertyquerty

**Comment by qwertyquerty** [comment]
Supply me with a quality Issue. I think it goes without saying that you should always supply the code.

**Comment by Arny4** [comment]
This error always happens in any code. And the error itself shows that the reason is in the pypresence itself.

**Comment by GhostofGoes** [comment]
What version of PyPresence do you have installed and what is your code?

**Comment by Arny4** [comment]
latest ver. This error appears in any code. @GhostofGoes

**Comment by GhostofGoes** [comment]
It works for me on Python 3.6.8 on Windows 10, and Python 3.6.6 and 3.7.2 on Ubuntu, so the code is fine. What version of Windows are you on? How did you install pypresence?

Possibilities:
* Something in your environment/system is causing an issue
* There's a bug in your code (which we can't help with unless we can see your code...)

**Comment by Arny4** [comment]
@GhostofGoes Windows 7.

**Comment by GhostofGoes** [comment]
That could be the reason then. Don't have a Win7 VM to test with right now, if I get some time this weekend I'll spin up a Vagrant box and look.

Can you share your code?

**Comment by Arny4** [comment]
Yes, @GhostofGoes . Check [this](https://github.com/Arny4/Discord-Presence-Editor), file Editor.pyw .

**Comment by isugimpy** [comment]
@qwertyquerty The report is hard to read, but I've pinned down the issue.  If you call .close() on a Presence object, it actually closes the event loop.  The problem is that you're using the global event loop by default, if no other one is provided, and there's no way to reopen it once it's closed.  I'm going to have a pull request for you momentarily with a really easy fix.

**Comment by isugimpy** [comment]
#70 should fix this issue.
