### ISSUE TITLE
How to get join request?

### ISSUE THREAD

**Issue by Gr4Yka** [qwertyquerty/pypresence#77]
I can throw an invitation to the game to a friend in discord chat, but how to get information about trying to connect

**Comment by minibox724** [comment]
I'm also curious

**Comment by FaderKing** [comment]
I'm also really interested in this

**Comment by CoopJax** [comment]
Check the dev docs
https://qwertyquerty.github.io/pypresence/html/doc/client.html?highlight=join%20request

**Comment by Hunter2807** [comment]
@Gr4Yka  pls close this issue if you are done, else join the discord server for better and faster support --> https://discord.gg/FSQmzwj3
