### ISSUE TITLE
Loop already running

### ISSUE THREAD

**Issue by MeridianPY** [qwertyquerty/pypresence#78]
Hi there.
I'm passing my own `asyncio.ProactorEventLoop()` to `pypresence.Presence()`, connecting and updating the RPC. After that I call a coroutine in the event loop that uses `rpc.update()` and I'm getting the error `RuntimeError: This event loop is already running`. Why is that, and how do I fix it?

My code, stripped down to the necessary stuff:

```python
loop = asyncio.ProactorEventLoop()
rpc = pypresence.Presence(client_id, loop=loop)
rpc.connect()
rpc.update(state='Test')
rpc.clear()
asyncio.set_event_loop(loop)

async def api():
    # doing some api calls here

async def set_presence(parameters):
    rpc.update(state='Test')

async def main():
    parameters = await api()
    await set_presence(parameters)
    await asyncio.sleep(15)

if __name__ == '__main__':
    loop.run_until_complete(main())
    rpc.close()
    loop.close()
```

I dont quite get how to add the loop to the RPC.

**Comment by Hunter2807** [comment]
@MeridianPY  pls close this issue if you are done, else join the discord server for better and faster support --> https://discord.gg/FSQmzwj3
