### ISSUE TITLE
Python 2 Support?

### ISSUE THREAD

**Issue by CrankySupertoon** [qwertyquerty/pypresence#79]

**Comment by LewdNeko** [comment]
No.

**Comment by CrankySupertoon** [comment]
Our game needs Python 2?

**Comment by qwertyquerty** [comment]
Is it definitely worth your time.

Even python 2.7 is now EOL. You should just upgrade already.

**Comment by CrankySupertoon** [comment]
This is for a 2 decade old Panda3D game

**Comment by LewdNeko** [comment]
You're more than welcome to port the code over yourself and make a PR for a separate branch, however we will not be adding or maintaining it ourselves.
