### ISSUE TITLE
Presence#update does nothing on the new Discord client

### ISSUE THREAD

**Issue by Rayzr522** [qwertyquerty/pypresence#84]
i'm hoping this is just a matter of me being blind and missing something, but i'm currently unable to get pypresence to actually display anything on Linux or Windows.

minimal script to reproduce:
```py
from pypresence import Presence
from time import sleep
from sys import exit

RPC = Presence('440997014315204609')
RPC.connect()
print("Sending update")
RPC.update(state='Hello', details='World')

while True:
    print("Sleeping...")
    try:
        sleep(15)
    except KeyboardInterrupt as e:
        RPC.close()
        print("RPC closed")
        exit(0)
```

i'm using virtualenv so it's a controlled environment in terms of python libs installed & python version used. my environment:

- Arch Linux (Kernel version 5.7.12)
  - Python 3.8.5 / 3.6.11 (tried both)
  - pypresence 3.2.2 / 4.0.0 (tried both, with both versions of python)
  - Discord 0.0.11 (the new client as of a few days ago)
- Windows 10
  - Python 3.7.4
  - pypresence 4.0.0
  - Latest Discord client (forgot to check version)

i'm hoping i'm wrong but i'm thinking maybe it's something changed with the new Discord client. it connects just fine, throws no errors when calling RPC.update, and in all senses seems to work just fine. the only problem being... no rich presence:

![image](https://user-images.githubusercontent.com/15263431/89932771-28156400-dbdc-11ea-9003-ba8e975e355b.png)

I've also tried a different client ID using a fresh Discord app in the developers portal, but no dice. same problem, it just doesn't update anything at all it seems.

> I'm also not the only one unable to get this to work, I have a simple program using pypresence called [discord-rpc-mpris](https://github.com/RayzrDev/discord-rpc-mpris) that is currently nonfunctional because of this. that's actually how this issue came to my attention, as a user tried to install discord-rpc-mpris, and it did nothing

**Comment by LewdNeko** [comment]
Not home atm, can't test sorry. Will respond properly in a few days

**Comment by coletonodonnell** [comment]
I also appear to have this issue as well, I have tried all the examples and his code. Still no response sadly. System details:
* Arch Linux 5.7.12-arch1-1
* Python 3.8.5-1
* Latest Discord Client (also forget the formal number but I don't have an update for it)

I was unable to get the code to work on either stable or development version of pypresence.

**Comment by coletonodonnell** [comment]
Actually, I take it back. After a look at discord-canary, this, along with any other rich presence item (VSCode for instance) seems to be working again. I think this isn't an issue with pypresence but rather stable. I typically use canary, but the AUR version is bugged right now and the maintainer is taking his sweet time to get it working, which is fine as I'll just use stable, but for this it kind of sucks.

**Comment by LewdNeko** [comment]
> Actually, I take it back. After a look at discord-canary, this, along with any other rich presence item (VSCode for instance) seems to be working again. I think this isn't an issue with pypresence but rather stable. I typically use canary, but the AUR version is bugged right now and the maintainer is taking his sweet time to get it working, which is fine as I'll just use stable, but for this it kind of sucks.

I don't know what the "AUR Version" is but If this is referring to anyone who maintains a repository for free and out of their spare time, you shouldn't really be bashing them about how long they're taking to get it working.
If its something that you pay for, ignore this message 👍

**Comment by coletonodonnell** [comment]
AUR is the Arch User Repository, with user-maintained packages. I was being more sarcastic in my explanation, obviously, if I really cared I would just maintain the canary version myself, I even said that the time wait is fine as "I'd just use stable." Though, I don't know what your comment you followed up with nor this discussion we're having has to do with the issue at hand, which is stable not reflecting Rich Presence on the Arch Linux platform (at minimum) and whether or not this is an issue with this library or just Discord's end.

**Comment by Rayzr522** [comment]
why was this issue closed? seems like it still merits investigation, especially since it was not just Arch Linux that had this issue for me but Windows as well (both using the latest Discord stable client). if it's something broken with pypresence on potentially all platforms, that sounds like something worth digging deeper into

**Comment by coletonodonnell** [comment]
> why was this issue closed? seems like it still merits investigation, especially since it was not just Arch Linux that had this issue for me but Windows as well (both using the latest Discord stable client). if it's something broken with pypresence on potentially all platforms, that sounds like something worth digging deeper into (if only to find out whether it's pypresence or Discord itself)

I don't know why it was closed, gonna have to assume the issue is with discord, though a comment confirming that belief would be nice. Honestly I just wanted to write an application for something and as long as I was able to test it, I was content. Though, if you haven't found a solution that isn't very fun. Have you tested canary on Windows?

**Comment by LewdNeko** [comment]
No clue why it Qwerty closed it but try passing pipe=1 when you create an instance of `Presence`. Discord uses different pipes for different Discord builds, or at least they did when this lib was made

**Comment by coletonodonnell** [comment]
> No clue why it Qwerty closed it but try passing pipe=1 when you create an instance of `Presence`. Discord uses different pipes for different Discord builds, or at least they did when this lib was made 

Is there a way to detect the current running instance of discord and determine if it's Canary or Stable? That way we can use different pipes for each respective one?

**Comment by LewdNeko** [comment]
Maybe checking running porcesses for Discord, DiscordCanary, etc
