### ISSUE TITLE
Improves documentation about event handling

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [qwertyquerty/pypresence#88]
Hi, I am a bit confused about the list of events that I can listen to in `register_event()`. I saw that in https://github.com/discord/discord-rpc/pull/167 you used to have a event documentation in `README.md#events` but seems that it has been removed?  

Maybe we should remake that?

**Comment by Hunter2807** [comment]
@Pythonic-Rainbow  pls close this issue if you are done, else join the discord server for better and faster support --> https://discord.gg/FSQmzwj3
