### ISSUE TITLE
Out of date examples and lack of documentation

### ISSUE THREAD

**Issue by metronode-uk** [qwertyquerty/pypresence#93]
Is there an up to date example on how to perform Client authentication? The [example listed in the examples folder](https://github.com/qwertyquerty/pypresence/blob/master/examples/client-authorize-example.md) is out of date by 2 years and the 5th line (`code_grant = auth.code`) throws an error.

The example listed is also not helpful in saying "exchange code grant for token, **rtfd**" when the docs don't explain how to do that exactly.

There is also a [hastebin paste in #announcements in your Discord server](https://canary.discord.com/channels/499601462347956253/499602680881086464/662879483665186867) (which presumably demonstrated how to perform client auth) however it is a dead link.

**Comment by Hunter2807** [comment]
![image](https://user-images.githubusercontent.com/46440327/103009796-50837680-455d-11eb-9bdb-93cf97e2e3e1.png)
see this @metronode-uk

**Comment by Hunter2807** [comment]
@metronode-uk pls close this issue if you are done, else join the discord server for better and faster support --> https://discord.gg/FSQmzwj3
