### ISSUE TITLE
Starting handshake loop taking very long

### ISSUE THREAD

**Issue by ellwoodb** [qwertyquerty/pypresence#94]
The `RPC.connect()` command is taking a lot of time (like 5 Seconds).

**Comment by KhushC-03** [comment]
Mine takes even longer sometimes

**Comment by Hunter2807** [comment]
@ellwoodb if the issue is fixed, then close this issue, else join the official discord server here and ask for help --> https://discord.gg/FSQmzwj3

**Comment by LewdNeko** [comment]
Will re-open if more information provided.
