### ISSUE TITLE
A traceback error, idk why

### ISSUE THREAD

**Issue by Hunter2807** [qwertyquerty/pypresence#95]
<h2>This is the whole error-</h2>

Traceback (most recent call last):
  File "C:\Users\myste\Desktop\some stuff\Lawliet AIO\OOOOOOOOOOF.py", line 7, in <module>
    RPC.update(state="Wawiet Host", details="hewwo onii chan~ pwease join https://discord.gg/<invite-deleted> fow cheap and fwee hosting!")
  File "C:\Python39\lib\site-packages\pypresence\presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Python39\lib\site-packages\pypresence\baseclient.py", line 102, in read_output
    status_code, length = struct.unpack('<II', data[:8])
struct.error: unpack requires a buffer of 8 bytes

<h2>This is the code-</h2>

from pypresence import Presence
import time

client_id = <removed-it>
RPC = Presence(client_id=client_id)
RPC.connect()
RPC.update(state="Wawiet Host", details="hewwo onii chan~ pwease join https://discord.gg/<invite-deleted> fow cheap and fwee hosting!")
while True:
    time.sleep(15)

**Comment by VeKett** [comment]
I don't currently have it installed so I can't tell but I'm fairly certain you don't need to put `Presence(client_id=client_id)` and can instead just put `Presence(client_id)` whether this is the issue or not, i am not certain.

Follow the example: [](https://github.com/qwertyquerty/pypresence/blob/master/examples/rich-presence.py)

**Comment by Hunter2807** [comment]
Thanks @VeKett i will try that!

**Comment by Dark42ed** [comment]
I've found that the error is because the socket is not recieving any data (`b''`) and is trying to decode that data, which would result in an error. I figure it happens because this is getting depreciated in favor of Discord's [Game SDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)
