### ISSUE TITLE
Script running, but nothing is happening on discord

### ISSUE THREAD

**Issue by WindowsVistaisCool** [qwertyquerty/pypresence#96]
Here is my code:
```py
from pypresence import Presence
import time

client_id = "797509614736113674"
RPC = Presence(client_id)
RPC.connect()

RPC.update(state="Hello world!")

while True:
    time.sleep(15)
```
I know I'm probably doing something wrong, but I've looked through the docs, the internet, and whatever else, but I couldn't find anything, so I have to resort to opening an issue here. If you need anything, ask me in the comments, and I'll try to respond.

**Comment by WindowsVistaisCool** [comment]
When I paste an invalid id, it throws an exception, so I think my client ID is okay.

**Comment by Hum4n01d** [comment]
Same issue here, it dumps out the log info in the terminal (every runs) but it doesn't actually do anything to Discord

**Comment by Hum4n01d** [comment]
Actually, just found the issue (at least for me). Check if you have game activity disabled, if you do, it won't show 
![image](https://user-images.githubusercontent.com/17228477/104755226-09794300-570f-11eb-951c-c8b2348833ad.png)

**Comment by Hunter2807** [comment]
Yup, u have to make sure that you have game activity enabled on discord. Then only it will show you they status on discord haha

**Comment by WindowsVistaisCool** [comment]
Okay thanks, I will test this on a windows machine later this week, as mine is in for repair (warranty stuff), but I am fairly sure I had this on. Thanks, and I will close this issue when I test.

**Comment by WindowsVistaisCool** [comment]
it now throws this error :/
```bash
Traceback (most recent call last):
  File ".\main.py", line 8, in <module>
    RPC.update(state="Hello world!")
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pypresence\presence.py", line 34, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pypresence\baseclient.py", line 103, in read_output
    status_code, length = struct.unpack('<II', preamble[:8])
struct.error: unpack requires a buffer of 8 bytes
```
same exact code

**Comment by Hunter2807** [comment]
@WindowsVistaisCool tbh it would be better if you join the official discord server, so that we can help you better. Here is the link to the same --> https://discord.gg/vYQ2uzUHPD

**Comment by WindowsVistaisCool** [comment]
Alright, I'll close this issue and ask on the discord.
